name: Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "SPEC/**"
      - "config.yaml.example"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Lint
        run: make lint

  test:
    name: Test
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Run tests
        run: make test
